### ISSUE TITLE
PSF Parameters

### ISSUE THREAD

**Issue by JulienNGirard** [CosmoStat/ShapeDeconv#15]
We have to select ranges of source RA & DEC that could fit observations of length 1 2 4 8

- constraint: MeerKAT fixed in SA
- selection in delta vs Delta T
- selection of "appropriate" RA  (first pick a fixed date, later, deduced correct RA that fit delta & DT)
- weighting of circumpolar sources vs near horizon sources

**Comment by fadinammour** [comment]
To do:

- [ ] solve PSF generation bug (gridder).
- [ ] generate different samples for a delta T = 2h.
- [ ] compute a constant standard noise deviation (Julien: find a typical sigma for MeerKat antennas).
- [ ] finish the end-to-end radio galaxy simulation notebook.

**Comment by JulienNGirard** [comment]
about task #3:
- [ ] #1) choose obs length (e.g. 2h)
- [ ] #2) trim distribution of elevation vs. max length  D= [-90,decl_lim]
- [ ] #3) draw uniform distribution of source declination in D
- [ ] #4) for each source of declination d, retrieve HAmin HAmax  T=[HAmin,HAmax]
- [ ] #5) draw uniform start HA_start in [HAmin,HAmax-Duration]

**Comment by JulienNGirard** [comment]
filling task N°3 subtasks

**Comment by JulienNGirard** [comment]
done
